#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-oauth2
Version  : 1.0.0
Release  : 5
URL      : https://rubygems.org/downloads/oauth2-1.0.0.gem
Source0  : https://rubygems.org/downloads/oauth2-1.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-bundler
BuildRequires : rubygem-coveralls
BuildRequires : rubygem-devise
BuildRequires : rubygem-diff-lcs
BuildRequires : rubygem-docile
BuildRequires : rubygem-domain_name
BuildRequires : rubygem-faraday
BuildRequires : rubygem-http-cookie
BuildRequires : rubygem-jwt
BuildRequires : rubygem-mime-types
BuildRequires : rubygem-multi_json
BuildRequires : rubygem-multi_xml
BuildRequires : rubygem-multipart-post
BuildRequires : rubygem-netrc
BuildRequires : rubygem-rack
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rest-client
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-simplecov-html
BuildRequires : rubygem-term-ansicolor
BuildRequires : rubygem-thor
BuildRequires : rubygem-tins
BuildRequires : rubygem-unf
BuildRequires : rubygem-unf_ext

%description
# OAuth2
[![Gem Version](http://img.shields.io/gem/v/oauth2.svg)][gem]
[![Build Status](http://img.shields.io/travis/intridea/oauth2.svg)][travis]
[![Dependency Status](http://img.shields.io/gemnasium/intridea/oauth2.svg)][gemnasium]
[![Code Climate](http://img.shields.io/codeclimate/github/intridea/oauth2.svg)][codeclimate]
[![Coverage Status](http://img.shields.io/coveralls/intridea/oauth2.svg)][coveralls]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n oauth2-1.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-oauth2.gemspec

%build
gem build rubygem-oauth2.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
oauth2-1.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/oauth2-1.0.0
rspec -I.:lib spec/
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/oauth2-1.0.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/cdesc-AccessToken.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/client-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/delete-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/expired%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/expires%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/expires_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/expires_in-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/from_hash-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/from_kvform-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/patch-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/post-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/put-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/refresh%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/refresh_token-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/token%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/AccessToken/token-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/assertion-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/auth_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/authorize_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/cdesc-Client.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/client_credentials-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/connection-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/get_token-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/id-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/implicit-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/password-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/secret-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/site%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/site-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Client/token_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Error/code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Error/description-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Error/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Error/response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/MACToken/algorithm%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/MACToken/algorithm-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/MACToken/cdesc-MACToken.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/MACToken/from_access_token-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/MACToken/header-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/MACToken/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/MACToken/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/MACToken/request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/MACToken/secret-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/MACToken/signature-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/MACToken/strict_encode64-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/MACToken/token%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Response/body-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Response/cdesc-Response.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Response/content_type-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Response/error-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Response/headers-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Response/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Response/options-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Response/parsed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Response/parser-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Response/register_parser-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Response/response-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Response/status-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/Assertion/authorize_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/Assertion/build_assertion-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/Assertion/build_request-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/Assertion/cdesc-Assertion.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/Assertion/get_token-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/AuthCode/authorize_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/AuthCode/authorize_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/AuthCode/cdesc-AuthCode.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/AuthCode/get_token-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/Base/client_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/Base/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/ClientCredentials/authorization-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/ClientCredentials/authorize_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/ClientCredentials/cdesc-ClientCredentials.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/ClientCredentials/get_token-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/Implicit/authorize_params-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/Implicit/authorize_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/Implicit/cdesc-Implicit.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/Implicit/get_token-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/Password/authorize_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/Password/cdesc-Password.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/Password/get_token-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Strategy/cdesc-Strategy.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Version/cdesc-Version.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/Version/to_s-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/OAuth2/cdesc-OAuth2.ri
/usr/lib64/ruby/gems/2.2.0/doc/oauth2-1.0.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/.document
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/LICENSE.md
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/.last_run.json
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/.resultset.json
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/.resultset.json.lock
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/application.css
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/application.js
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/colorbox/border.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/colorbox/controls.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/colorbox/loading.gif
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/colorbox/loading_background.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/favicon_green.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/favicon_red.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/favicon_yellow.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/loading.gif
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/magnify.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/smoothness/images/ui-bg_flat_0_aaaaaa_40x100.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/smoothness/images/ui-bg_flat_75_ffffff_40x100.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_55_fbf9ee_1x400.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_65_ffffff_1x400.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_75_dadada_1x400.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_75_e6e6e6_1x400.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/smoothness/images/ui-bg_glass_95_fef1ec_1x400.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/smoothness/images/ui-bg_highlight-soft_75_cccccc_1x100.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/smoothness/images/ui-icons_222222_256x240.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/smoothness/images/ui-icons_2e83ff_256x240.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/smoothness/images/ui-icons_454545_256x240.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/smoothness/images/ui-icons_888888_256x240.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/assets/0.10.0/smoothness/images/ui-icons_cd0a0a_256x240.png
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/coverage/index.html
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/lib/oauth2.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/lib/oauth2/access_token.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/lib/oauth2/client.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/lib/oauth2/error.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/lib/oauth2/mac_token.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/lib/oauth2/response.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/lib/oauth2/strategy/assertion.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/lib/oauth2/strategy/auth_code.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/lib/oauth2/strategy/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/lib/oauth2/strategy/client_credentials.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/lib/oauth2/strategy/implicit.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/lib/oauth2/strategy/password.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/lib/oauth2/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/oauth2.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/spec/helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/spec/oauth2/access_token_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/spec/oauth2/client_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/spec/oauth2/mac_token_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/spec/oauth2/response_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/spec/oauth2/strategy/assertion_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/spec/oauth2/strategy/auth_code_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/spec/oauth2/strategy/base_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/spec/oauth2/strategy/client_credentials_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/spec/oauth2/strategy/implicit_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/oauth2-1.0.0/spec/oauth2/strategy/password_spec.rb
/usr/lib64/ruby/gems/2.2.0/specifications/oauth2-1.0.0.gemspec
