#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-oauth2
Version  : 1.1.0
Release  : 8
URL      : https://rubygems.org/downloads/oauth2-1.1.0.gem
Source0  : https://rubygems.org/downloads/oauth2-1.1.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-addressable
BuildRequires : rubygem-http-cookie
BuildRequires : rubygem-jwt
BuildRequires : rubygem-mime-types
BuildRequires : rubygem-multi_json
BuildRequires : rubygem-multi_xml
BuildRequires : rubygem-multipart-post
BuildRequires : rubygem-netrc
BuildRequires : rubygem-rack
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rest-client
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-rspec-expectations
BuildRequires : rubygem-rspec-mocks
BuildRequires : rubygem-rspec-support
BuildRequires : rubygem-simplecov
BuildRequires : rubygem-simplecov-html
BuildRequires : rubygem-term-ansicolor
BuildRequires : rubygem-thor
BuildRequires : rubygem-tins
BuildRequires : rubygem-unf
BuildRequires : rubygem-unf_ext

%description
# OAuth2
[![Gem Version](http://img.shields.io/gem/v/oauth2.svg)][gem]
[![Build Status](http://img.shields.io/travis/intridea/oauth2.svg)][travis]
[![Dependency Status](http://img.shields.io/gemnasium/intridea/oauth2.svg)][gemnasium]
[![Code Climate](http://img.shields.io/codeclimate/github/intridea/oauth2.svg)][codeclimate]
[![Coverage Status](http://img.shields.io/coveralls/intridea/oauth2.svg)][coveralls]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n oauth2-1.1.0
gem spec %{SOURCE0} -l --ruby > rubygem-oauth2.gemspec

%build
gem build rubygem-oauth2.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
oauth2-1.1.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/oauth2-1.1.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/.document
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/CONTRIBUTING.md
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/LICENSE.md
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2.rb
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2/access_token.rb
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2/client.rb
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2/error.rb
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2/mac_token.rb
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2/response.rb
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2/strategy/assertion.rb
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2/strategy/auth_code.rb
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2/strategy/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2/strategy/client_credentials.rb
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2/strategy/implicit.rb
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2/strategy/password.rb
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/lib/oauth2/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/oauth2-1.1.0/oauth2.gemspec
/usr/lib64/ruby/gems/2.3.0/specifications/oauth2-1.1.0.gemspec
